[project]
name = "chess-project"
version = "0.1.0"
description = "Sucden Financial chess coding project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "python-chess>=1.999",
    "typer>=0.20.0",
]
